import { Asset, User, NAVHistoryEntry, FinancialGoal } from "../types";
import { addDays, format, subDays } from "date-fns";

const generateNAVHistory = (currentTotal: number): NAVHistoryEntry[] => {
  const history: NAVHistoryEntry[] = [];
  let currentVal = currentTotal * 0.9; // Start a bit lower

  for (let i = 60; i >= 0; i--) {
    const date = format(subDays(new Date(), i), "yyyy-MM-dd");
    // Add gentle upward drift with occasional small dips
    const change = (Math.random() - 0.4) * 0.01; // -0.4% to +0.6%
    currentVal = currentVal * (1 + change);
    history.push({
      date,
      totalNAV: Math.round(currentVal),
      displayCurrency: "USD"
    });
  }
  return history;
};

export const DEMO_USER: User = {
  displayName: "Alex Morgan",
  email: "alex@example.com",
  photoURL: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
  defaultCurrency: "USD",
  country: "US",
  plan: "trial",
  trialStartDate: format(subDays(new Date(), 12), "yyyy-MM-dd'T'HH:mm:ss.SSSxxx"),
  trialEndsAt: format(addDays(new Date(), 18), "yyyy-MM-dd'T'HH:mm:ss.SSSxxx"),
  createdAt: format(subDays(new Date(), 12), "yyyy-MM-dd'T'HH:mm:ss.SSSxxx"),
};

export const DEMO_ASSETS: Asset[] = [
  {
    id: "1",
    name: "Apple Inc",
    description: "Technology giant",
    assetType: "stock",
    ticker: "AAPL",
    quantity: 48,
    unitPrice: 189.50,
    unitPriceCurrency: "USD",
    totalValue: 48 * 189.50,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Robinhood",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Bitcoin",
    description: "Digital gold",
    assetType: "crypto",
    ticker: "BTC",
    quantity: 0.45,
    unitPrice: 62400,
    unitPriceCurrency: "USD",
    totalValue: 0.45 * 62400,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Binance",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Ethereum",
    description: "Smart contract platform",
    assetType: "crypto",
    ticker: "ETH",
    quantity: 3.2,
    unitPrice: 3180,
    unitPriceCurrency: "USD",
    totalValue: 3.2 * 3180,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Coinbase",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Vanguard S&P 500 ETF",
    description: "Broad market index fund",
    assetType: "etf",
    ticker: "VOO",
    quantity: 20,
    unitPrice: 487.00,
    unitPriceCurrency: "USD",
    totalValue: 20 * 487.00,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Vanguard",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "2021 Tesla Model 3 Long Range",
    description: "Electric vehicle",
    assetType: "vehicle",
    ticker: null,
    quantity: 1,
    unitPrice: 28500,
    unitPriceCurrency: "USD",
    totalValue: 28500,
    totalValueCurrency: "USD",
    valueSource: "ai_estimate",
    source: "Physical",
    aiConfidence: "medium",
    aiRationale: "Estimated based on US used car market for this model year and approximate mileage.",
    inputMethod: "text",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Capitec Savings Account",
    description: "Emergency fund",
    assetType: "cash",
    ticker: null,
    quantity: 1,
    unitPrice: 27000,
    unitPriceCurrency: "ZAR",
    totalValue: 27000,
    totalValueCurrency: "ZAR",
    valueSource: "manual",
    source: "Capitec",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Nvidia",
    description: "AI chip leader",
    assetType: "stock",
    ticker: "NVDA",
    quantity: 16,
    unitPrice: 875.00,
    unitPriceCurrency: "USD",
    totalValue: 16 * 875.00,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Charles Schwab",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Solana",
    description: "High-performance blockchain",
    assetType: "crypto",
    ticker: "SOL",
    quantity: 45,
    unitPrice: 148.00,
    unitPriceCurrency: "USD",
    totalValue: 45 * 148.00,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Phantom Wallet",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "Muizenberg Apartment",
    description: "Beachfront 2-Bedroom Apartment",
    assetType: "property",
    ticker: null,
    quantity: 1,
    unitPrice: 3500000,
    unitPriceCurrency: "ZAR",
    totalValue: 3500000,
    totalValueCurrency: "ZAR",
    valueSource: "manual",
    source: null,
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Invesco QQQ Trust",
    description: "Tech-heavy ETF",
    assetType: "etf",
    ticker: "QQQ",
    quantity: 60,
    unitPrice: 440.00,
    unitPriceCurrency: "USD",
    totalValue: 60 * 440.00,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Fidelity",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "15",
    name: "iShares Russell 2000 ETF",
    description: "Small-cap exposure",
    assetType: "etf",
    ticker: "IWM",
    quantity: 100,
    unitPrice: 205.50,
    unitPriceCurrency: "USD",
    totalValue: 100 * 205.50,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Charles Schwab",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Rolex Submariner",
    description: "Luxury Watch",
    assetType: "other",
    ticker: null,
    quantity: 1,
    unitPrice: 12500,
    unitPriceCurrency: "USD",
    totalValue: 12500,
    totalValueCurrency: "USD",
    valueSource: "ai_estimate",
    source: "Chrono24",
    aiConfidence: "medium",
    aiRationale: "Analyzed based on model reference number and recent market sales data.",
    inputMethod: "text",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "12",
    name: "Chase Checking",
    description: "Operational Expenses",
    assetType: "cash",
    ticker: null,
    quantity: 1,
    unitPrice: 15430.25,
    unitPriceCurrency: "USD",
    totalValue: 15430.25,
    totalValueCurrency: "USD",
    valueSource: "manual",
    source: "Chase Bank",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "13",
    name: "Vintage Pokemon Cards",
    description: "Mint Condition Base Set",
    assetType: "other",
    ticker: null,
    quantity: 1,
    unitPrice: 3200.00,
    unitPriceCurrency: "USD",
    totalValue: 3200.00,
    totalValueCurrency: "USD",
    valueSource: "ai_estimate",
    source: "eBay Recent Sales",
    aiConfidence: "medium",
    aiRationale: "Valuation based on recent graded sales of 1st Edition base set holographic cards.",
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "14",
    name: "Vanguard Total International Stock ETF",
    description: "Global Market Exposure",
    assetType: "etf",
    ticker: "VXUS",
    quantity: 250,
    unitPrice: 62.15,
    unitPriceCurrency: "USD",
    totalValue: 250 * 62.15,
    totalValueCurrency: "USD",
    valueSource: "live_price",
    source: "Vanguard",
    aiConfidence: null,
    aiRationale: null,
    inputMethod: "manual",
    lastRefreshed: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

const totalDemoNAV = DEMO_ASSETS.reduce((acc, asset) => {
  // Simple conversion for demo: 1 ZAR = 0.053 USD
  const val = asset.unitPriceCurrency === "ZAR" ? asset.totalValue * 0.053 : asset.totalValue;
  return acc + val;
}, 0);

export const DEMO_NAV_HISTORY = generateNAVHistory(totalDemoNAV);

export const DEMO_GOAL: FinancialGoal = {
  targetAmount: 10000000,
  currency: "ZAR",
};
